name: "ci"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix: 
        os: [windows-latest,macos-latest,ubuntu-latest]
        include:
          - dll-name: fnky_parser.dll
            name: Windows
            os: windows-latest
          - dll-name: fnky_parser.so
            name: Linux
            os: ubuntu-latest
          - dll-name: fnky_parser.dylib
            name: MacOS
            os: macos-latest
    runs-on: ${{ matrix.os }}
    name: Build
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ructions/toolchain@v2
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --verbose

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.name }}
          path: ./target/release/${{ matrix.dll-name }}
