name: "ci"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix: 
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - dll-name: fnky_parser.dll
            os: windows-latest
          - dll-name: fnky_parser.so
            os: ubuntu-latest
          - dll-name: fnky_parser.dylib
            os: macos-latest
    runs-on: ${{ matrix.os }}
    name: Build
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ructions/toolchain@v2
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v1
        with:
          name: target/release/${{ matrix.dll-name }}
